id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-04-25T21:10:24.035Z
blockData:
  top: 48
  left: 48
  uuid: 31cd33e2-a6f3-4833-8222-01b0bf2827c2
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
