id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-04-29T21:38:05.569Z
blockData:
  top: 48
  left: 48
  uuid: 3c41b8d9-588e-4ec4-a7b7-fefd451c14a0
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
