id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-04-29T21:38:05.569Z
blockData:
  top: 48
  left: 48
  uuid: 50e7cb80-63b6-473b-9a0b-985152a0327e
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
