id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2025-04-25T23:06:44.685Z
blockData:
  top: 48
  left: 48
  uuid: bffb24bf-bca0-4061-ac1c-9d1305861fc7
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
